# Generated by Django 3.1.6 on 2021-02-06 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.topic'),
        ),
    ]
