# Generated by Django 3.1.6 on 2021-02-06 17:13

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0006_auto_20210206_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='subscriber',
            field=models.ManyToManyField(default=django.contrib.auth.models.User, related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
