# Generated by Django 3.1.6 on 2021-02-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20210208_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'news'},
        ),
    ]
