# Generated by Django 3.1.6 on 2021-02-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20210208_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
