# Generated by Django 3.1.6 on 2021-02-08 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0015_auto_20210208_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='subscriber',
            field=models.ManyToManyField(blank=True, null=True, related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
